// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcXyE-VSYUg_zQH7HSXOK9zfnV-nVm2KI',
    appId: '1:746781902444:web:b1a3e165afc471a6bafa49',
    messagingSenderId: '746781902444',
    projectId: 'lab3-mis-firebase',
    authDomain: 'lab3-mis-firebase.firebaseapp.com',
    storageBucket: 'lab3-mis-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdbMgu6PSlRcekM5PQJSaZv8sPoiFuLA',
    appId: '1:746781902444:android:a2d2d99011bfeabcbafa49',
    messagingSenderId: '746781902444',
    projectId: 'lab3-mis-firebase',
    storageBucket: 'lab3-mis-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxdb8_2KIZowk_Zio8axaSTlSiD-v6gKg',
    appId: '1:746781902444:ios:14b7ec6d93928302bafa49',
    messagingSenderId: '746781902444',
    projectId: 'lab3-mis-firebase',
    storageBucket: 'lab3-mis-firebase.firebasestorage.app',
    iosBundleId: 'com.mis.lab3.lab3Mis',
  );
}
